* FreeBSD on Vagrant
** TODO Restore the pkg configuration to default
We are setting the pkg site to the wunki server. This should be restored to
default.
** DONE Don't show the boot menu
   CLOSED: [2013-10-25 Fri 13:13]
   - State "DONE"       from "TODO"       [2013-10-25 Fri 13:13]
The boot menu takes ten seconds to show, that's just a waste of time in a
headless VM.
** DONE Cleanup pkg's after installation
   CLOSED: [2013-10-25 Fri 13:39]
   - State "DONE"       from "TODO"       [2013-10-25 Fri 13:39]
Clean the package cache because it saves some space.
** DONE Destroy all history
   CLOSED: [2013-10-25 Fri 13:35]
   - State "DONE"       from "TODO"       [2013-10-25 Fri 13:35]
Destroy all the shell history.
** TODO Minimize disk space
=dd= all the empty space and remove it again. This also saves space when
packaging the box.
** DONE Edit the MOTD (/etc/motd)
   CLOSED: [2013-10-25 Fri 13:20]
   - State "DONE"       from "TODO"       [2013-10-25 Fri 13:20]
Add a pretty MOTD.
** TODO Document Virtualbox settings
Virtualbox needs some specific settings to boot a FreeBSD ISO. Add that
information to the README so people can start from scratch on their own.
** TODO Upload the box Vagrantbox.es
Add the box to Vagrantbox.es to spread the reach of the most awesome operating
system out there.
