* FreeBSD on Vagrant
** DONE Restore the pkg configuration to default
   CLOSED: [2013-10-26 Sat 11:47]
   - State "DONE"       from "TODO"       [2013-10-26 Sat 11:47]
We are setting the pkg site to the wunki server. This should be restored to
default.
** DONE Don't show the boot menu
   CLOSED: [2013-10-25 Fri 13:13]
   - State "DONE"       from "TODO"       [2013-10-25 Fri 13:13]
The boot menu takes ten seconds to show, that's just a waste of time in a
headless VM.
** DONE Cleanup pkg's after installation
   CLOSED: [2013-10-25 Fri 13:39]
   - State "DONE"       from "TODO"       [2013-10-25 Fri 13:39]
Clean the package cache because it saves some space.
** DONE Destroy all history
   CLOSED: [2013-10-25 Fri 13:35]
   - State "DONE"       from "TODO"       [2013-10-25 Fri 13:35]
Destroy all the shell history.
** DONE Minimize disk space
   CLOSED: [2013-10-25 Fri 13:45]
   - State "DONE"       from "TODO"       [2013-10-25 Fri 13:45]
=dd= all the empty space and remove it again. This also saves space when
packaging the box.
** DONE Edit the MOTD (/etc/motd)
   CLOSED: [2013-10-25 Fri 13:20]
   - State "DONE"       from "TODO"       [2013-10-25 Fri 13:20]
Add a pretty MOTD.
** DONE Document Virtualbox settings
   CLOSED: [2013-10-25 Fri 20:17]
   - State "DONE"       from "TODO"       [2013-10-25 Fri 20:17]
Virtualbox needs some specific settings to boot a FreeBSD ISO. Add that
information to the README so people can start from scratch on their own.
** DONE Upload the box Vagrantbox.es
   CLOSED: [2013-10-25 Fri 20:18]
   - State "DONE"       from "TODO"       [2013-10-25 Fri 20:18]
Add the box to Vagrantbox.es to spread the reach of the most awesome operating
system out there.
